services:
  server:
    image: ascherer82/sourcedepth.com:latest
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    volumes:
      - ./mdx:/usr/src/app/mdx
      - ./public:/usr/src/app/public
  nginx:
    depends_on:
      - server
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    restart: always
  certbot:
    profiles:
      - certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot/ --email andrew@sourcedepth.com -d sourcedepth.com --agree-tos --keep-until-expiring
