# Generated by Django 5.2.3 on 2025-07-07 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubworkflowrun',
            options={'ordering': ['-github_updated_at']},
        ),
    ]
