# Generated by Django 5.2.3 on 2025-06-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('github_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('node_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('gravatar_id', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('html_url', models.URLField(blank=True)),
                ('followers_url', models.URLField(blank=True)),
                ('following_url', models.URLField(blank=True)),
                ('gists_url', models.URLField(blank=True)),
                ('starred_url', models.URLField(blank=True)),
                ('subscriptions_url', models.URLField(blank=True)),
                ('organizations_url', models.URLField(blank=True)),
                ('repos_url', models.URLField(blank=True)),
                ('events_url', models.URLField(blank=True)),
                ('received_events_url', models.URLField(blank=True)),
                ('user_type', models.CharField(default='User', max_length=50)),
                ('user_view_type', models.CharField(default='default', max_length=50)),
                ('site_admin', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('blog', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hireable', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('twitter_username', models.CharField(blank=True, max_length=255)),
                ('public_repos', models.IntegerField(default=0)),
                ('public_gists', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_created_at', models.DateTimeField(blank=True, null=True)),
                ('github_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', '-updated_at'],
            },
        ),
    ]
