# Generated by Django 5.2.3 on 2025-06-24 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubuser',
            name='last_fetched',
        ),
    ]
