name: Build 🏗️ and Deploy 🚀 to VPS

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"
      - run: npm install
      - run: npm run build --if-present
      - uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: dist
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to VPS
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-build
      - run: ls dist
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            echo "Deploying to VPS..."
            rm -rf ~/sourcedepth.com/dist
            cp -r dist ~/sourcedepth.com/
            echo "Deployment complete!"
